FROM python:3.8-alpine
RUN adduser -D abagdemo
WORKDIR /home/abagdemo
COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip3 install -r requirements.txt

COPY boot.sh boot.sh
RUN chmod +x boot.sh
COPY main.py main.py
COPY instance instance
COPY project project

ENV FLASK_APP main.py
RUN chown -R abagdemo:abagdemo ./
USER abagdemo

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]